module.exports = {

  letters: [
    {
      id: 1,
      capital: 'A',
      lowercase: 'a',
      capitalSound: '/sounds/capitalSounds/A.mp3',
      lowerSound: '/sounds/lowerSounds/a.wav',
      wordImage: [
        {id:1, image:'images/words/ahi.svg', sound: 'sounds/ahi.m4a'},
        {id:2, image:'images/words/anuhe.svg', sound: 'sounds/anuhe.m4a'},
        {id:3, image:'images/words/aroha.svg', sound: 'sounds/aroha.m4a'},
      ],
      multimedia: '/multimedia/anuhe.mp4',
      mediaName: 'Anuhe - Caterpillar',
    },
    {
      id: 2,
      capital: 'E',
      lowercase: 'e',
      capitalSound: '/sounds/capitalSounds/E.mp3',
      lowerSound: '/sounds/lowerSounds/e.wav',
      wordImage: [
        {id:1, image:'images/words/eo.svg', sound: 'sounds/eo.m4a'},
        {id:2, image:'images/words/ekara.svg', sound: 'sounds/ekara.m4a'},
        {id:3, image:'images/words/placeholder.png', sound: 'sounds/epapou.m4a'},
      ],
      multimedia: '/multimedia/ekara.mp4',
      mediaName: 'Ekara - Eagle',
    },
    {
      id: 3,
      capital: 'H',
      lowercase: 'h',
      capitalSound: '/sounds/capitalSounds/H.mp3',
      lowerSound: '/sounds/lowerSounds/h.wav',
      wordImage: [
        {id:1, image:'images/words/placeholder.png', sound: 'sounds/harakeke.m4a'},
        {id:2, image:'images/words/hoiho.svg', sound: 'sounds/hoiho.m4a'},
        {id:3, image:'images/words/placeholder.png', sound: 'sounds/harikoa.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Hoiho - Horse',
    },
    {
      id: 4,
      capital: 'I',
      lowercase: 'i',
      capitalSound: '/sounds/capitalSounds/I.mp3',
      lowerSound: '/sounds/lowerSounds/i.wav',
      wordImage: [
        {id:1, image:'images/words/ika.svg', sound:  'sounds/ika.m4a'},
        {id:2, image:'images/words/placeholder.png', sound: 'sounds/ihu.m4a'},
        {id:3, image:'images/words/irirangi.svg', sound:  'sounds/irirangi.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Ihu waiata',
    },
    {
      id: 5,
      capital: 'K',
      lowercase: 'k',
      capitalSound: '/sounds/capitalSounds/K.mp3',
      lowerSound: '/sounds/lowerSounds/k.wav',
      wordImage: [
        {id:1, image:'images/words/kaki.svg', sound:  '/sounds/kaki.m4a'},
        {id:2, image:'images/words/kakariki.svg', sound:  '/sounds/kakariki.m4a'},
        {id:3, image:'images/words/koura.svg', sound: 'sounds/koura.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'colours waiata',
    },
    {
      id: 6,
      capital: 'M',
      lowercase: 'm',
      capitalSound: '/sounds/capitalSounds/M.mp3',
      lowerSound: '/sounds/lowerSounds/m.wav',
      wordImage: [
        {id:1, image:'images/words/maunga.svg', sound:  '/sounds/maunga.m4a'},
        {id:2, image:'images/words/manu.svg', sound:  '/sounds/manu.m4a'},{id:3, image:'images/words/makawe.svg', sound: 'sounds/makawe.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Manu - Birds',
    },
    {
      id: 7,
      capital: 'N',
      lowercase: 'n',
      capitalSound: '/sounds/capitalSounds/N.mp3',
      lowerSound: '/sounds/lowerSounds/n.wav',
      wordImage: [
        {id:1, image:'images/words/niho.svg', sound:  '/sounds/niho.m4a'},
        {id:2, image:'images/words/noke.svg', sound:  '/sounds/noke.m4a'},
        {id:3, image:'images/words/placeholder.png', sound: 'sounds/nikau.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Noke - worm',
    },
    {
      id: 8,
      capital: 'Ng',
      lowercase: 'ng',
      capitalSound: '/sounds/capitalSounds/NG.mp3',
      lowerSound: '/sounds/lowerSounds/ng.wav',
      wordImage: [
        {id:1, image:'images/words/ngahere.svg', sound:  '/sounds/ngahere.m4a'},
        {id:2, image:'images/words/ngata.svg', sound:  '/sounds/ngata.m4a'},
        {id:3, image:'images/words/ngutu.svg', sound: 'sounds/ngutu.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Ngata movie',
    },
    {
      id: 9,
      capital: 'O',
      lowercase: 'o',
      capitalSound: '/sounds/capitalSounds/O.mp3',
      lowerSound: '/sounds/lowerSounds/o.wav',
      wordImage: [
        {id:1, image:'images/words/one.svg', sound:  '/sounds/one.m4a'},
        {id:2, image:'images/words/ora.svg', sound:  '/sounds/ora.m4a'},
        {id:3, image:'images/words/oru.svg', sound: 'sounds/oru.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Ora - health',
    },
    {
      id: 10,
      capital: 'P',
      lowercase: 'p',
      capitalSound: '/sounds/capitalSounds/P.mp3',
      lowerSound: '/sounds/lowerSounds/p.wav',
      wordImage: [
        {id:1, image:'images/words/placeholder.png', sound:  '/sounds/poi.m4a'},
        {id:2, image:'images/words/pungawerewere.svg', sound:  '/sounds/pungawerewere.m4a'},
        {id:3, image:'images/words/placeholder.png', sound: 'sounds/puku.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Pungawerewere - spider',
    },
    {
      id: 11,
      capital: 'R',
      lowercase: 'r',
      capitalSound: '/sounds/capitalSounds/R.mp3',
      lowerSound: '/sounds/lowerSounds/r.wav',
      wordImage: [
        {id:1, image:'images/words/ruru.svg', sound:  '/sounds/ruru.m4a'},
        {id:2, image:'images/words/ringa.svg', sound:  '/sounds/ringa.m4a'},
        {id:3, image:'images/words/placeholder.png', sound: 'sounds/rangi.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Ringa - Hand',
    },
    {
      id: 12,
      capital: 'T',
      lowercase: 't',
      capitalSound: '/sounds/capitalSounds/T.mp3',
      lowerSound: '/sounds/lowerSounds/t.wav',
      wordImage: [
        {id:1, image:'images/words/placeholder.png', sound:  '/sounds/tinana.m4a'},
        {id:2, image:'images/words/tohora.svg', sound:  '/sounds/tohora.m4a'},
        {id:3, image:'images/words/placeholder.png', sound: 'sounds/tuatara.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Tohora - Whale',
    },
    {
      id: 13,
      capital: 'U',
      lowercase: 'u',
      capitalSound: '/sounds/capitalSounds/U.mp3',
      lowerSound: '/sounds/lowerSounds/u.wav',
      wordImage: [
        {id:1, image:'images/words/placeholder.png', sound:  '/sounds/ua.m4a'},
        {id:2, image:'images/words/placeholder.png', sound:  '/sounds/upoko.m4a'},
        {id:3, image:'images/words/placeholder.png', sound: 'sounds/ururoa.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Rain rain go away',
    },
    {
      id: 14,
      capital: 'W',
      lowercase: 'w',
      capitalSound: '/sounds/capitalSounds/W.mp3',
      lowerSound: '/sounds/lowerSounds/w.wav',
      wordImage: [
        {id:1, image:'images/words/placeholder.png', sound:  '/sounds/weta.m4a'},
        {id:2, image:'images/words/placeholder.png', sound:  '/sounds/wai.m4a'},
        {id:3, image:'images/words/placeholder.png', sound: 'sounds/waewae.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'The Weta Animation',
    },
    {
      id: 15,
      capital: 'Wh',
      lowercase: 'wh',
      capitalSound: '/sounds/capitalSounds/WH.mp3',
      lowerSound: '/sounds/lowerSounds/wh.wav',
      wordImage: [
        {id:1, image:'images/words/placeholder.png', sound:  '/sounds/whatu.m4a'},
        {id:2, image:'images/words/placeholder.png', sound:  '/sounds/wheke.m4a'},
        {id:3, image:'images/words/placeholder.png', sound: 'sounds/whenua.m4a'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'The whanau rhyme',
    },
  ],
  letter: {},
  completed: 0,
}
