module.exports = {

  letters: [
    {
      id: 1,
      capital: 'A',
      lowercase: 'a',
      capitalSound: '/sounds/capitalSounds/A.mp3',
      lowerSound: '/sounds/lowerSounds/a.wav',
      wordImage: [
        {id:1, image:'images/words/ahi.svg', sound: 'sounds/ahi.m4a', description: 'ahi'},
        {id:2, image:'images/words/anuhe.svg', sound: 'sounds/anuhe.m4a', description: 'anuhe'},
        {id:3, image:'images/words/aroha.svg', sound: 'sounds/aroha.m4a', description: 'aroha'},
      ],
      multimedia: '/multimedia/anuhe.mp4',
      mediaName: 'Anuhe - Caterpillar',
    },
    {
      id: 2,
      capital: 'E',
      lowercase: 'e',
      capitalSound: '/sounds/capitalSounds/E.mp3',
      lowerSound: '/sounds/lowerSounds/e.wav',
      wordImage: [
        {id:1, image:'images/words/eo.svg', sound: 'sounds/eo.m4a', description: 'eo'},
        {id:2, image:'images/words/peke.svg', sound: 'sounds/peke.m4a', description: 'peke'},
        {id:3, image:'images/words/kete.svg', sound: 'sounds/kete.m4a', description: 'kete'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Peke - Jump',
    },
    {
      id: 3,
      capital: 'H',
      lowercase: 'h',
      capitalSound: '/sounds/capitalSounds/H.mp3',
      lowerSound: '/sounds/lowerSounds/h.wav',
      wordImage: [
        {id:1, image:'images/words/harakeke.svg', sound: 'sounds/harakeke.m4a', description: 'harakeke'},
        {id:2, image:'images/words/hoiho.svg', sound: 'sounds/hoiho.m4a', description: 'hoiho'},
        {id:3, image:'images/words/harikoa.svg', sound: 'sounds/harikoa.m4a', description: 'harikoa'},
      ],
      multimedia: '/multimedia/hoiho.mp4',
      mediaName: 'Hoiho - Horse',
    },
    {
      id: 4,
      capital: 'I',
      lowercase: 'i',
      capitalSound: '/sounds/capitalSounds/I.mp3',
      lowerSound: '/sounds/lowerSounds/i.wav',
      wordImage: [
        {id:1, image:'images/words/ika.svg', sound:  'sounds/ika.m4a', description: 'ika'},
        {id:2, image:'images/words/ihu.svg', sound: 'sounds/ihu.m4a', description: 'ihu'},
        {id:3, image:'images/words/irirangi.svg', sound:  'sounds/irirangi.m4a', description: 'irirangi'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Ihu waiata',
    },
    {
      id: 5,
      capital: 'K',
      lowercase: 'k',
      capitalSound: '/sounds/capitalSounds/K.mp3',
      lowerSound: '/sounds/lowerSounds/k.wav',
      wordImage: [
        {id:1, image:'images/words/kai.svg', sound:  '/sounds/kai.m4a', description: 'kai'},
        {id:2, image:'images/words/kakariki.svg', sound:  '/sounds/kakariki.m4a', description: 'kākāriki'},
        {id:3, image:'images/words/koura.svg', sound: 'sounds/koura.m4a', description: 'koura'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'colours waiata',
    },
    {
      id: 6,
      capital: 'M',
      lowercase: 'm',
      capitalSound: '/sounds/capitalSounds/M.mp3',
      lowerSound: '/sounds/lowerSounds/m.wav',
      wordImage: [
        {id:1, image:'images/words/maunga.svg', sound:  '/sounds/maunga.m4a', description: 'maunga'},
        {id:2, image:'images/words/manu.svg', sound:  '/sounds/manu.m4a', description: 'manu'},
        {id:3, image:'images/words/makawe.svg', sound: 'sounds/makawe.m4a', description: 'makawe'},
      ],
      multimedia: '/multimedia/manu.mp4',
      mediaName: 'Manu - Bird',
    },
    {
      id: 7,
      capital: 'N',
      lowercase: 'n',
      capitalSound: '/sounds/capitalSounds/N.mp3',
      lowerSound: '/sounds/lowerSounds/n.wav',
      wordImage: [
        {id:1, image:'images/words/niho.svg', sound:  '/sounds/niho.m4a', description: 'niho'},
        {id:2, image:'images/words/noke.svg', sound:  '/sounds/noke.m4a', description: 'noke'},
        {id:3, image:'images/words/nikau.svg', sound: 'sounds/nikau.m4a', description: 'nikau'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Noke - worm',
    },
    {
      id: 8,
      capital: 'Ng',
      lowercase: 'ng',
      capitalSound: '/sounds/capitalSounds/NG.mp3',
      lowerSound: '/sounds/lowerSounds/ng.wav',
      wordImage: [
        {id:1, image:'images/words/ngahere.svg', sound:  '/sounds/ngahere.m4a', description: 'ngahere'},
        {id:2, image:'images/words/ngata.svg', sound:  '/sounds/ngata.m4a', description: 'ngata'},
        {id:3, image:'images/words/ngutu.svg', sound: 'sounds/ngutu.m4a', description: 'ngutu'},
      ],
      multimedia: '/multimedia/ngata.mp4',
      mediaName: 'Ngata - Snail',
    },
    {
      id: 9,
      capital: 'O',
      lowercase: 'o',
      capitalSound: '/sounds/capitalSounds/O.mp3',
      lowerSound: '/sounds/lowerSounds/o.wav',
      wordImage: [
        {id:1, image:'images/words/one.svg', sound:  '/sounds/one.m4a', description: 'one'},
        {id:2, image:'images/words/ora.svg', sound:  '/sounds/ora.m4a', description: 'ora'},
        {id:3, image:'images/words/oru.svg', sound: 'sounds/oru.m4a', description: 'oru'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Ora - health',
    },
    {
      id: 10,
      capital: 'P',
      lowercase: 'p',
      capitalSound: '/sounds/capitalSounds/P.mp3',
      lowerSound: '/sounds/lowerSounds/p.wav',
      wordImage: [
        {id:1, image:'images/words/poi.svg', sound:  '/sounds/poi.m4a', description: 'poi'},
        {id:2, image:'images/words/pungawerewere.svg', sound:  '/sounds/pungawerewere.m4a', description: 'pūngāwerewere'},
        {id:3, image:'images/words/paraoa.svg', sound: 'sounds/paraoa.m4a', description: 'paraoa'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Pungawerewere - spider',
    },
    {
      id: 11,
      capital: 'R',
      lowercase: 'r',
      capitalSound: '/sounds/capitalSounds/R.mp3',
      lowerSound: '/sounds/lowerSounds/r.wav',
      wordImage: [
        {id:1, image:'images/words/ruru.svg', sound:  '/sounds/ruru.m4a', description: 'ruru'},
        {id:2, image:'images/words/ringa.svg', sound:  '/sounds/ringa.m4a', description: 'ringa'},
        {id:3, image:'images/words/rangi.svg', sound: 'sounds/rangi.m4a', description: 'rangi'},
      ],
      multimedia: '/multimedia/ringa.mp4',
      mediaName: 'Ringa - Hand',
    },
    {
      id: 12,
      capital: 'T',
      lowercase: 't',
      capitalSound: '/sounds/capitalSounds/T.mp3',
      lowerSound: '/sounds/lowerSounds/t.wav',
      wordImage: [
        {id:1, image:'images/words/tinana.svg', sound:  '/sounds/tinana.m4a', description: 'tinana'},
        {id:2, image:'images/words/tohora.svg', sound:  '/sounds/tohora.m4a', description: 'tohorā'},
        {id:3, image:'images/words/tuatara.svg', sound: 'sounds/tuatara.m4a', description: 'tuatara'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'Tohora - Whale',
    },
    {
      id: 13,
      capital: 'U',
      lowercase: 'u',
      capitalSound: '/sounds/capitalSounds/U.mp3',
      lowerSound: '/sounds/lowerSounds/u.wav',
      wordImage: [
        {id:1, image:'images/words/upoko.svg', sound:  '/sounds/upoko.m4a', description: 'upoko'},
        {id:2, image:'images/words/ua.svg', sound:  '/sounds/ua.m4a', description: 'ua'},
        {id:3, image:'images/words/ururoa.svg', sound: 'sounds/ururoa.m4a', description: 'ururoa'},
      ],
      multimedia: '/multimedia/ua.mp4',
      mediaName: 'Ua - Rain',
    },
    {
      id: 14,
      capital: 'W',
      lowercase: 'w',
      capitalSound: '/sounds/capitalSounds/W.mp3',
      lowerSound: '/sounds/lowerSounds/w.wav',
      wordImage: [
        {id:1, image:'images/words/waewae.svg', sound:  '/sounds/waewae.m4a', description: 'waewae'},
        {id:2, image:'images/words/waka.svg', sound:  '/sounds/waka.m4a', description: 'waka'},
        {id:3, image:'images/words/wai.svg', sound: 'sounds/wai.m4a', description: 'wai'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'The Weta Animation',
    },
    {
      id: 15,
      capital: 'Wh',
      lowercase: 'wh',
      capitalSound: '/sounds/capitalSounds/WH.mp3',
      lowerSound: '/sounds/lowerSounds/wh.wav',
      wordImage: [
        {id:1, image:'images/words/whatu.svg', sound:  '/sounds/whatu.m4a', description: 'whatu'},
        {id:2, image:'images/words/wheke.svg', sound:  '/sounds/wheke.m4a', description: 'wheke'},
        {id:3, image:'images/words/whare.svg', sound: 'sounds/whare.m4a', description: 'whare'},
      ],
      multimedia: '/multimedia/wheke.mp4',
      mediaName: 'Wheke - Octopus',
    },
    {
      id: 16,
      capital: 'Ā',
      lowercase: 'ā',
      capitalSound: '/sounds/capitalSounds/AA.mp3',
      lowerSound: '/sounds/lowerSounds/a.wav',
      wordImage: [
        {id:1, image:'images/words/aporo.svg', sound:  '/sounds/aporo.m4a', description: 'āporo'},
        {id:2, image:'images/words/aniwaniwa.svg', sound:  '/sounds/aniwaniwa.m4a', description: 'āniwaniwa'},
        {id:3, image:'images/words/arani.svg', sound: 'sounds/arani.m4a', description: 'ārani'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'The whanau rhyme',
    },
    {
      id: 17,
      capital: 'Ē',
      lowercase: 'ē',
      capitalSound: '/sounds/capitalSounds/EE.mp3',
      lowerSound: '/sounds/lowerSounds/e.wav',
      wordImage: [
        {id:1, image:'images/words/weta.svg', sound:  '/sounds/weta.m4a', description: 'wētā'},
        {id:2, image:'images/words/ekara.svg', sound:  '/sounds/ekara.m4a', description: 'ēkara'},
        {id:3, image:'images/words/pekana.svg', sound: 'sounds/pekana.m4a', description: 'pēkana'},
      ],
      multimedia: '/multimedia/ekara.mp4',
      mediaName: 'Eagle - ēkara',
    },
    {
      id: 18,
      capital: 'Ī',
      lowercase: 'ī',
      capitalSound: '/sounds/capitalSounds/II.mp3',
      lowerSound: '/sounds/lowerSounds/i.wav',
      wordImage: [
        {id:1, image:'images/words/tihi.svg', sound:  '/sounds/tihi.m4a', description: 'tīhi'},
        {id:2, image:'images/words/kaki.svg', sound:  '/sounds/kaki.m4a', description: 'kakī'},
        {id:3, image:'images/words/miti.svg', sound: 'sounds/miti.m4a', description: 'mīti'},
      ],
      multimedia: '/multimedia/aniwaniwa.webm',
      mediaName: 'The whanau rhyme',
    },
    {
      id: 19,
      capital: 'Ō',
      lowercase: 'ō',
      capitalSound: '/sounds/capitalSounds/OO.mp3',
      lowerSound: '/sounds/lowerSounds/o.wav',
      wordImage: [
        {id:1, image:'images/words/totiti.svg', sound:  '/sounds/totiti.m4a', description:  'tōtiti'},
        {id:2, image:'images/words/netiporo.svg', sound:  '/sounds/netiporo.m4a', description: 'netipōro'},
        {id:3, image:'images/words/tohi.svg', sound: 'sounds/tohi.m4a', description: 'tōhi'},
      ],
      multimedia: '/multimedia/netiporo.mp4',
      mediaName: 'Netipōro - Netball',
    },
    {
      id: 20,
      capital: 'Ū',
      lowercase: 'ū',
      capitalSound: '/sounds/capitalSounds/UU.mp3',
      lowerSound: '/sounds/lowerSounds/u.wav',
      wordImage: [
        {id:1, image:'images/words/turu.svg', sound:  '/sounds/turu.m4a', description: 'tūrū'},
        {id:2, image:'images/words/purerehua.svg', sound: 'sounds/purerehua.m4a', description: 'pūrerehua'},
        {id:3, image:'images/words/hapu.svg', sound:  '/sounds/hapu.m4a', description: 'hapū'},
      ],
      multimedia: '/multimedia/purerehua.mp4',
      mediaName: 'Pūrerehua - Butterfly',
    },
  ],
  letter: {},
  completed: 0,
}
