
module.exports = {

  letters: [
    {
      id: 1,
      capital: "A",
      lowercase: "a",
      capitalSound: "/sounds/capitalSounds/A.mp3",
      lowerSound: "/sounds/lowerSounds/a.mp3",
      wordImage: [
        {id:1, image:"images/words/aniwaniwa.png", sound: "sounds/ua.mp3"},
        {id:2, image:"images/words/anuhe.png", sound: "sounds/anuhe.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Aniwaniwa Song",
    },
    {
      id: 2,
      capital: "E",
      lowercase: "e",
      capitalSound: "/sounds/capitalSounds/E.mp3",
      lowerSound: "/sounds/lowerSounds/e.mp3",
      wordImage: [
        {id:1, image:"images/words/ekara.png", sound: "sounds/ekara.mp3"},
        {id:2, image:"images/words/ekara.png", sound: "sounds/ekara.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Ekara Animation",
    },
    {
      id: 3,
      capital: "H",
      lowercase: "h",
      capitalSound: "/sounds/capitalSounds/H.mp3",
      lowerSound: "/sounds/lowerSounds/h.mp3",
      wordImage: [
        {id:1, image:"images/words/hoiho.png", sound: "sounds/hoiho.mp3"},
        {id:2, image:"images/words/heki.png", sound: "sounds/heki.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Hoiho Song",
    },
    {
      id: 4,
      capital: "I",
      lowercase: "i",
      capitalSound: "/sounds/capitalSounds/I.mp3",
      lowerSound: "/sounds/lowerSounds/i.mp3",
      wordImage: [
        {id:1, image:"images/words/ika.png", sound:  "sounds/ika.mp3"},
        {id:2, image:"images/words/ika.png", sound:  "sounds/ika.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Ika Animation",
    },
    {
      id: 5,
      capital: "K",
      lowercase: "k",
      capitalSound: "/sounds/capitalSounds/K.mp3",
      lowerSound: "/sounds/lowerSounds/k.mp3",
      wordImage: [
        {id:1, image:"images/words/koura.png", sound:  "/sounds/koura.mp3"},
        {id:2, image:"images/words/kanga.png", sound:  "/sounds/kanga.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Koura song",
    },
    {
      id: 6,
      capital: "M",
      lowercase: "m",
      capitalSound: "/sounds/capitalSounds/M.mp3",
      lowerSound: "/sounds/lowerSounds/m.mp3",
      wordImage: [
        {id:1, image:"images/words/maunga.png", sound:  "/sounds/maunga.mp3"},
        {id:2, image:"images/words/moana.png", sound:  "/sounds/moana.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Maunga Animation",
    },
    {
      id: 7,
      capital: "N",
      lowercase: "n",
      capitalSound: "/sounds/capitalSounds/N.mp3",
      lowerSound: "/sounds/lowerSounds/n.mp3",
      wordImage: [
        {id:1, image:"images/words/nanikoti.png", sound:  "/sounds/nanikoti.mp3"},
        {id:2, image:"images/words/noke.png", sound:  "/sounds/noke.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Nanikoti Rhyme",
    },
    {
      id: 8,
      capital: "Ng",
      lowercase: "ng",
      capitalSound: "/sounds/capitalSounds/NG.mp3",
      lowerSound: "/sounds/lowerSounds/ng.mp3",
      wordImage: [
        {id:1, image:"images/words/ngata.png", sound:  "/sounds/ngata.mp3"},
        {id:2, image:"images/words/ngata.png", sound:  "/sounds/ngata.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Ngata animation",
    },
    {
      id: 9,
      capital: "O",
      lowercase: "o",
      capitalSound: "/sounds/capitalSounds/O.mp3",
      lowerSound: "/sounds/lowerSounds/o.mp3",
      wordImage: [
        {id:1, image:"images/words/oru.png", sound:  "/sounds/oru.mp3"},
        {id:2, image:"images/words/ono.png", sound:  "/sounds/ono.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Oru animation",
    },
    {
      id: 10,
      capital: "P",
      lowercase: "p",
      capitalSound: "/sounds/capitalSounds/P.mp3",
      lowerSound: "/sounds/lowerSounds/p.mp3",
      wordImage: [
        {id:1, image:"images/words/pungawerewere.png", sound:  "/sounds/pungawerewere.mp3"},
        {id:2, image:"images/words/purerehua.png", sound:  "/sounds/purerehua.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Incy wincy spider",
    },
    {
      id: 11,
      capital: "R",
      lowercase: "r",
      capitalSound: "/sounds/capitalSounds/R.mp3",
      lowerSound: "/sounds/lowerSounds/r.mp3",
      wordImage: [
        {id:1, image:"images/words/ruru.png", sound:  "/sounds/ruru.mp3"},
        {id:2, image:"images/words/ranginui.png", sound:  "/sounds/ranginui.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "The Ruru Song",
    },
    {
      id: 12,
      capital: "T",
      lowercase: "t",
      capitalSound: "/sounds/capitalSounds/T.mp3",
      lowerSound: "/sounds/lowerSounds/t.mp3",
      wordImage: [
        {id:1, image:"images/words/tanemahuta.png", sound:  "/sounds/tanemahuta.mp3"},
        {id:2, image:"images/words/tamanuitera.png", sound:  "/sounds/tamanuitera.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Tane mahuta legend",
    },
    {
      id: 13,
      capital: "U",
      lowercase: "u",
      capitalSound: "/sounds/capitalSounds/U.mp3",
      lowerSound: "/sounds/lowerSounds/u.mp3",
      wordImage: [
        {id:1, image:"images/words/ua.png", sound:  "/sounds/ua.mp3"},
        {id:2, image:"images/words/uenuku.png", sound:  "/sounds/ua.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "Rain rain go away",
    },
    {
      id: 14,
      capital: "W",
      lowercase: "w",
      capitalSound: "/sounds/capitalSounds/W.mp3",
      lowerSound: "/sounds/lowerSounds/w.mp3",
      wordImage: [
        {id:1, image:"images/words/weta.png", sound:  "/sounds/weta.mp3"},
        {id:2, image:"images/words/wai.png", sound:  "/sounds/wai.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "The Weta Animation",
    },
    {
      id: 15,
      capital: "Wh",
      lowercase: "wh",
      capitalSound: "/sounds/capitalSounds/WH.mp3",
      lowerSound: "/sounds/lowerSounds/wh.mp3",
      wordImage: [
        {id:1, image:"images/words/whanau.png", sound:  "/sounds/whanau.mp3"},
        {id:2, image:"images/words/whanau.png", sound:  "/sounds/whanau.mp3"},
      ],
      multimedia: "/multimedia/aniwaniwa.webm",
      mediaName: "The whanau rhyme",
    },
  ],
  letter: {},
}
